#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
MACHETE_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

BIN="$MACHETE_DIR/build_cmake_release/test_machete_gemm"
SHAPES_FILE=""
OUT_CACHE="$MACHETE_DIR/cutlass55_tactics_h800.cache"
OUT_MD="$MACHETE_DIR/CUTLASS55_TACTICS_H800.md"
WARMUP=20
ITERS=100
QUANT=cutlass_s4
APPEND=0

usage() {
  cat <<'USAGE'
Usage: machete_standalone/scripts/search_cutlass55_tactics.sh [options]

Options:
  --bin PATH          test_machete_gemm binary
  --shapes PATH       shape file; each non-comment line: M N K GROUP ACT
  --out-cache PATH    tactic cache output
  --out-md PATH       markdown table output
  --warmup N
  --iters N
  --quant NAME        default: cutlass_s4
  --append            append to existing cache/markdown instead of truncating

The script runs CUTLASS55 configs sequentially for each shape and stores only
the fastest config in the cache:

  m,n,k,group,act|config=<name>,avg_us=<time>
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bin) BIN="$2"; shift 2 ;;
    --shapes) SHAPES_FILE="$2"; shift 2 ;;
    --out-cache) OUT_CACHE="$2"; shift 2 ;;
    --out-md) OUT_MD="$2"; shift 2 ;;
    --warmup) WARMUP="$2"; shift 2 ;;
    --iters) ITERS="$2"; shift 2 ;;
    --quant) QUANT="$2"; shift 2 ;;
    --append) APPEND=1; shift ;;
    --help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ ! -x "$BIN" ]]; then
  echo "Binary not found or not executable: $BIN" >&2
  exit 1
fi

if [[ "$APPEND" -eq 0 ]]; then
  {
    echo "# CUTLASS55 tactic cache"
    echo "# Generated by machete_standalone/scripts/search_cutlass55_tactics.sh"
    echo "# Format: m,n,k,group,act|config=<name>,avg_us=<time>"
  } > "$OUT_CACHE"
  {
    echo "# CUTLASS55 Tactics"
    echo
    echo "Command:"
    echo
    echo '```bash'
    echo "machete_standalone/scripts/search_cutlass55_tactics.sh --warmup $WARMUP --iters $ITERS"
    echo '```'
    echo
    echo "| M | N | K | Group | Act | Best config | Avg time (us) | Effective TFLOPS |"
    echo "|---:|---:|---:|---:|---|---|---:|---:|"
  } > "$OUT_MD"
fi

read -r -d '' DEFAULT_SHAPES <<'SHAPES' || true
# M N K GROUP ACT
1 4096 4096 128 fp16
16 4096 4096 128 fp16
64 4096 4096 128 fp16
128 4096 4096 128 fp16
256 4096 4096 128 fp16
512 4096 4096 128 fp16
1024 4096 4096 128 fp16
2048 4096 4096 128 fp16
4096 4096 4096 128 fp16
3823 3072 2048 128 fp16
3823 1024 3072 128 fp16
3823 12288 2048 128 fp16
3823 2048 3072 128 fp16
SHAPES

run_shape() {
  local m="$1"
  local n="$2"
  local k="$3"
  local group="$4"
  local act="$5"
  local log="/tmp/cutlass55_tactic_${m}_${n}_${k}_${group}_${act}.$$.log"

  echo "===== search CUTLASS55 m=$m n=$n k=$k group=$group act=$act ====="
  "$BIN" \
    --backend=cutlass55 \
    --search_cutlass55_configs \
    --m="$m" --n="$n" --k="$k" --group_size="$group" \
    --act="$act" --quant="$QUANT" \
    --offline_prepack --no_checksum \
    --warmup="$WARMUP" --iters="$ITERS" \
    --save_cutlass55_tactic="$OUT_CACHE" \
    2>&1 | tee "$log"

  local best_line config avg_us tflops
  best_line=$(grep "Best CUTLASS55 config:" "$log" | tail -n 1 || true)
  if [[ -z "$best_line" ]]; then
    echo "Failed to parse best config for m=$m n=$n k=$k" >&2
    exit 1
  fi
  config=$(awk '{print $4}' <<< "$best_line")
  avg_us=$(sed -n 's/.*avg_us=\([0-9.]*\).*/\1/p' <<< "$best_line")
  tflops=$(awk -v m="$m" -v n="$n" -v k="$k" -v us="$avg_us" 'BEGIN { printf "%.1f", 2.0*m*n*k/(us*1e-6)/1e12 }')
  echo "| $m | $n | $k | $group | $act | \`$config\` | $avg_us | $tflops |" >> "$OUT_MD"
}

if [[ -n "$SHAPES_FILE" ]]; then
  while read -r m n k group act rest; do
    [[ -z "${m:-}" || "$m" == \#* ]] && continue
    run_shape "$m" "$n" "$k" "$group" "$act"
  done < "$SHAPES_FILE"
else
  while read -r m n k group act rest; do
    [[ -z "${m:-}" || "$m" == \#* ]] && continue
    run_shape "$m" "$n" "$k" "$group" "$act"
  done <<< "$DEFAULT_SHAPES"
fi

echo "Wrote cache: $OUT_CACHE"
echo "Wrote table: $OUT_MD"
